language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql
  - composer update --dev

script:
  - phpunit --configuration phpunit.travis.xml
